#!/bin/sh

PRJ=`grep -v '\#' PACKAGES`

for i in `for i in $PRJ ; do ls -d $i* ; done` ; do
    if [ -f $i/bootstrap ] ; then
	echo "*** bootstraping $i"
	(cd $i && ./bootstrap) || exit 1
    fi
done
