#!/bin/sh

make bootstrap

# PRJ=`grep -v '\#' PACKAGES`
# 
# for i in `for i in $PRJ ; do ls -d $i* | head -1 ; done` ; do
#     if [ -f $i/bootstrap ] ; then
# 	echo "*** bootstrapping $i"
# 	(cd $i && ./bootstrap) || exit 1
#     fi
# done
